export const AppRoutes = {
  Dashboard: "/",
  Upgrade: "/upgrade",
  Clients: "/clients",
  Products: "/products",
  Invoices: "/invoices",
  RecurringInvoices: "/recurring-invoices",
  Payments: "/payments",
  Quotes: "/quotes",
  Credits: "/credits",
  Projects: "/projects",
  Tasks: "/tasks",
  Vendors: "/vendors",
  PurchaseOrders: "/purchase-orders",
  Expenses: "/expenses",
  RecurringExpenses: "/recurring-expenses",
  Transactions: "/transactions",
  Reports: "/reports",
  Settings: "/settings",
};
